config/routes.rb
Rails.application.routes.draw do
  
  get 'reports/index'
  get 'reports/sales_report'
  get 'reports/customer_registered'
  get 'reports/coupon_used'
  resources :recommended_products
  resources :contacts
  resources :wishlists
  resources :transactions
  resources :orders do
    member do
      get 'cancel_order'
    end
  end
  resources :coupons
  resources :addresses
  resources :checkouts  
  get :payment_review, to: 'checkouts#payment_review'
  get :check_coupon_code, to: 'checkouts#check_coupon_code'
  resources :cart_items
  resources :product_categories
  resources :products
  resources :brand_categories
  resources :charges do
    member do
      get 'payment'
    end
  end
  resources :products
  resources :categories do
    resources :brands
  end
  resources :brands
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'home#index'
  get '*abc', :to => 'home#routing_error'

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :user
  has_many :orders
end

app/models/banner.rb
class Banner < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  has_many :pictures, as: :imageable
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  default_scope  { order(:name => :desc) }
  has_many :brand_categories
  has_many :categories, :through => :brand_categories
  has_many :products
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :user
  belongs_to :product

  def self.cart_total(cart_items,session)
    sub_total = 0
    discount = 0
    cart_items.each do |item|
      sub_total += (item.product.price.to_i * item.quantity.to_i) 
    end
    if session.present?
      coupon = Coupon.find_by(code: session)
      percent_off = coupon.percent_off
      discount = ((percent_off * sub_total) / 100)
      tax = 0.04 * sub_total
      shipping_cost = 40
      final_total = tax + sub_total + shipping_cost - discount
    else
      tax = 0.04 * sub_total
      shipping_cost = 40
      final_total = tax + sub_total + shipping_cost
    end
    return sub_total, discount, tax, shipping_cost, final_total
  end

  def self.update_cart(params_qty, params_quantity, cart_item)
    if params_qty == "minus"
      if cart_item.quantity == 1
        cart_item.quantity=1
      else
        cart_item.quantity -= 1
      end
    elsif params_qty == "plus"
      cart_item.quantity += 1
    else
      quantity = params_quantity.to_i
      if params_quantity == ""
        cart_item.quantity = @cart_item.quantity
      elsif params_quantity.to_i < 1
        cart_item.quantity = 1
      else
        cart_item.quantity = quantity
      end
    end
    return cart_item.quantity
  end

  def self.update_cart_item(cart_item, boolean, cart_item_quantity)
    if boolean.present?
      quantity_one = cart_item_quantity
      cart_item.quantity += quantity_one.to_i
    else
      cart_item.quantity += 1
    end
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :subcategories, class_name: "Category", foreign_key: "category_id", dependent: :destroy
  has_many :brands, :through => :brand_categories
  has_many :brand_categories
  belongs_to :category
  has_many :products, :through => :product_category
  has_many :product_category
end

app/models/checkout.rb
class Checkout < ActiveRecord::Base

  def self.cart_total(cart_items,session)
    sub_total = 0
    discount = 0
    cart_items.each do |item|
      sub_total += (item.product.price.to_i * item.quantity.to_i) 
    end
    if session.present?
      coupon = Coupon.find_by(code: session)
      percent_off = coupon.percent_off
      discount = ((percent_off * sub_total) / 100)
      tax = 0.04 * sub_total
      shipping_cost = 40
      final_total = tax + sub_total + shipping_cost - discount
    else
      tax = 0.04 * sub_total
      shipping_cost = 40
      final_total = tax + sub_total + shipping_cost
    end
    return sub_total,discount,tax,shipping_cost,final_total
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :user
end

app/models/coupon.rb
class Coupon < ActiveRecord::Base

  def self.destroy_coupon(cart_items, session)
    sub_total1 = 0
    discount = 0
    cart_items.each do |item|
      sub_total1 += (item.product.price.to_i * item.quantity.to_i) 
    end
    if session.present?
      coupon = Coupon.find_by(code: session)
      percent_off = coupon.percent_off
      discount = ((percent_off * sub_total1) / 100)
      tax = 0.04 * sub_total1
      shipping_cost = 40
      final_total = tax + sub_total1 + shipping_cost - discount
    else
      tax = 0.04 * sub_total1
      shipping_cost = 40
      final_total = tax + sub_total1 + shipping_cost
    end
    return sub_total1, discount, tax, shipping_cost, final_total
  end

end

app/models/coupon_used.rb
class CouponUsed < ActiveRecord::Base
  belongs_to :user
  belongs_to :order
  belongs_to :coupon
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :address
  has_many :orderitems
  default_scope -> { order(id: :desc) }
  after_update :track_order
  
  def track_order
    @order = Order.find(id)
    @track_order = Trackorder.new(status: @order.order_status, order_id: @order.id)
    @track_order.save
  end

  def self.set_sub_total(current_user)
    sub_total = 0
    current_user.cart_items.each do |item|
      sub_total += (item.product.price.to_i * item.quantity.to_i) 
    end
    return sub_total
  end
end

app/models/orderitem.rb
class Orderitem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :user
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :imageable, polymorphic: true
  mount_uploader :image, ImageUploader
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :pictures, as: :imageable
  belongs_to :brand
  has_many :product_category
  has_many :categories, :through => :product_category

  has_and_belongs_to_many(:products,
    :join_table => "recommended_products",
    :foreign_key => "product_id",
    :association_foreign_key => "recommended_product_id")
end

app/models/trackorder.rb
class Trackorder < ActiveRecord::Base
  belongs_to :order
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :user
  belongs_to :order
  belongs_to :orderitem
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  #validates :status, presence: true
  after_create :send_email
  has_many :wishlists, dependent: :destroy
  has_many :orders
  has_many :orderitems
  has_many :addresses
  has_many :coupon_useds
  has_many :transactions
  has_many :contacts
  devise :omniauthable, :omniauth_providers => [:facebook,:google_oauth2,:twitter]
  has_many :cart_items
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.firstname = auth.info.name
      user.password = Devise.friendly_token[0,20]
    end
  end
  
  def send_email
    UserMailer.welcome_email(self).deliver
  end       
end

app/models/wishlist.rb
class Wishlist < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @banners = Banner.all
    @categories = Category.all
    @category = Category.first
    @brands = Brand.all
  end
  
  def routing_error
    render partial: "/errors/error_404"
  end
  
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/views/home/_index_category.html.erb
<div class="category-tab"><!--category-tab-->
  <div class="col-sm-12">
    <ul class="nav nav-tabs">
      <%if @category.present? %>
        <% @categories.each_with_index do |subcategory, index| %>
          <% if subcategory.category_id == @category.id %>
            <%if @active.present?%>
              <li data-target="#slider-carousel" data-slide-to="<%= index %>" class="<%= @active.id == subcategory.id ? 'active' : '' %>"></li>
            <%else%>
              <li data-target="#slider-carousel" data-slide-to="<%= index %>" class="<%= index == 0 ? 'active' : '' %>"></li>
            <%end%>
            <li><%= link_to category_path(id: @category.id, sub_category: subcategory.id) do %>
              <%=subcategory.name%>
            <%end%></li>
          <%end%>
        <% end %>
      <%else%>
        Not present
      <%end%>
    </ul>
  </div>
  <div class="tab-content">
    <div class="tab-pane fade active in" id="tshirt" >
      <% if  @category.present? %>
      <%if @category.products.present?%>
        <% @category.products.each do |product|%>
          <div class="col-sm-3">
            <div class="product-image-wrapper">
              <div id="wishlist-<%=product.id%>">
                <%= render partial: "home/wish_list_tag", locals: {product: product} %>
              </div>
              <div class="single-products">
                <div class="productinfo text-center">
                  <%= link_to product_path(product)do%>
                    <% if product.pictures.find_by(imageable_id: product.id).present? %>
                      <%= image_tag product.pictures.first.image %>
                    <%end%>
                    <h2>Rs.<%=product.price%></h2>                      
                    <p><%= truncate(product.name, length: 22, omission: '...') %></p>
                  <%end%>
                  <%= link_to "Add to Cart", cart_items_path(product_id: product.id), method: :post, class: "fa fa-shopping-cart btn btn-default add-to-cart"%>
                </div> 
              </div>
            </div>
          </div>
        <%end%>
      <%end%>
      <%else%>
        not available
      <%end%>
    </div> 
  </div>
</div><!--/category-tab-->

app/views/home/_wish_list_tag.html.erb
<h4 align="right">
  <% if current_user.present? %>
    <% if current_user.present? && current_user.wishlists.pluck(:product_id).include?(product.id)%>
      <% wishlist = Wishlist.find_by(user_id: current_user.id, product_id: product.id)%>
      <%= link_to wishlist_path(wishlist), method: :delete, title: 'Remove from wishlist', remote: true do %>
        <i class="fa fa-heart wish_list_button" aria-hidden="true"></i>
      <%end%>
    <%else%>
      <%= link_to wishlists_path(product_id: product.id), method: :post, title: 'Add to wishlist', remote: true do %>
        <i class="fa fa-heart-o" aria-hidden="true"></i>
      <%end%>
    <%end%>
  <%else%>
    <% if current_user.present? && current_user.wishlists.pluck(:product_id).include?(product.id)%>
      <%= link_to wishlist_path(product), method: :delete, title: 'Remove from wishlist' do %>
        <i class="fa fa-heart wish_list_button" aria-hidden="true"></i>
      <%end%>
    <%else%>
      <%= link_to wishlists_path(product_id: product.id), method: :post, title: 'Add to wishlist' do %>
        <i class="fa fa-heart-o" aria-hidden="true"></i>
      <%end%>
    <%end%>
  <%end%>
</h4>

app/views/home/index.html.erb
<section>
  <div class="row">
    <div class="col-md-12">
      <%= render '/commonrender/slider'%>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-sm-3">
        <%= render '/commonrender/left_sidebar' %>
      </div>
      <div class="col-sm-9 padding-right">
        <%= render 'index_category' %>
      </div>
    </div>
  </div>
</section>