config/routes.rb
Rails.application.routes.draw do
  
  get 'reports/index'
  get 'reports/sales_report'
  get 'reports/customer_registered'
  get 'reports/coupon_used'
  resources :recommended_products
  resources :contacts
  resources :wishlists
  resources :transactions
  resources :orders do
    member do
      get 'cancel_order'
    end
  end
  resources :coupons
  resources :addresses
  resources :checkouts  
  get :payment_review, to: 'checkouts#payment_review'
  get :check_coupon_code, to: 'checkouts#check_coupon_code'
  resources :cart_items
  resources :product_categories
  resources :products
  resources :brand_categories
  resources :charges do
    member do
      get 'payment'
    end
  end
  resources :products
  resources :categories do
    resources :brands
  end
  resources :brands
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'home#index'
  get '*abc', :to => 'home#routing_error'

end

app/models/checkout.rb
class Checkout < ActiveRecord::Base

  def self.cart_total(cart_items,session)
    sub_total = 0
    discount = 0
    cart_items.each do |item|
      sub_total += (item.product.price.to_i * item.quantity.to_i) 
    end
    if session.present?
      coupon = Coupon.find_by(code: session)
      percent_off = coupon.percent_off
      discount = ((percent_off * sub_total) / 100)
      tax = 0.04 * sub_total
      shipping_cost = 40
      final_total = tax + sub_total + shipping_cost - discount
    else
      tax = 0.04 * sub_total
      shipping_cost = 40
      final_total = tax + sub_total + shipping_cost
    end
    return sub_total,discount,tax,shipping_cost,final_total
  end
end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
  before_action :set_checkout, only: [:show, :edit, :update, :destroy]
  before_action :set_checkouts, only: [:index, :payment_review]
  before_action :set_addresses, only:[:index, :payment_review]

  # GET /checkouts
  # GET /checkouts.json
  def index
    @cart_items = current_user.cart_items
    @sub_total, @discount, @tax, @shipping_cost, @final_total = CartItem.cart_total(@cart_items,session[:coupon_code])
  end

  # GET /checkouts/1
  # GET /checkouts/1.json
  def show
  end

  # GET /checkouts/new
  def new
    @checkout = Checkout.new
  end

  # GET /checkouts/1/edit
  def edit
  end

  # POST /checkouts
  # POST /checkouts.json
  def create
    @checkout = Checkout.new(checkout_params)
    respond_to do |format|
      if @checkout.save
        format.html { redirect_to @checkout, notice: 'Checkout was successfully created.' }
        format.json { render :show, status: :created, location: @checkout }
      else
        format.html { render :new }
        format.json { render json: @checkout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /checkouts/1
  # PATCH/PUT /checkouts/1.json
  def update
    respond_to do |format|
      if @checkout.update(checkout_params)
        format.html { redirect_to @checkout, notice: 'Checkout was successfully updated.' }
        format.json { render :show, status: :ok, location: @checkout }
      else
        format.html { render :edit }
        format.json { render json: @checkout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /checkouts/1
  # DELETE /checkouts/1.json
  def destroy
    @checkout.destroy
    respond_to do |format|
      format.html { redirect_to checkouts_url, notice: 'Checkout was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def payment_review
    @coupon = Coupon.new
    @cart_items = current_user.cart_items
    @sub_total, @discount, @tax, @shipping_cost, @final_total = CartItem.cart_total(@cart_items,session[:coupon_code])
    @address_id = params[:address_id]
  end

  def check_coupon_code
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_checkout
      @checkout = Checkout.find(params[:id])
    end

    def set_checkouts
      @checkouts = Checkout.all
    end

    def set_addresses
      @addresses = Address.new
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def checkout_params
      params.fetch(:checkout, {})
    end
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/views/checkouts/_address_form.html.erb
<div>
  <% address_type ||= 'billing_address' %>
  <%= f.text_field :name, placeholder: "First Name", name: "address[#{address_type}][name]" %>
  <%= f.text_field :email, placeholder: "Email", name: "address[#{address_type}][email]" %>
  <%= f.text_field :address_one, placeholder: "Address1", name: "address[#{address_type}][address_one]" %>
  <%= f.text_field :address_two, placeholder: "Address2", name: "address[#{address_type}][address_two]" %>
  <%= f.text_field :zip_code, placeholder: "Zip / Postal Code", name: "address[#{address_type}][zip_code]" %>
  <%= f.text_field :mobile_number, placeholder: "Mobile Phone", name: "address[#{address_type}][mobile_number]" %>
</div>

app/views/checkouts/_address_model_form.html.erb
<div class="modal-dialog model_dialog_one">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">&times;</button>
      <h4 class="modal-title">Add New Address</h4>
    </div>
    <div class="modal-body">
      <div class="shopper-informations">
        <div class="row">
          <%= form_for @addresses, :html => { :id=>'submit-form'} do |f| %>
            <div class="col-sm-12 clearfix">                 
              <div class="bill-to">
                <div class="form-one">
                    <%= f.text_field :name, placeholder: "Name", required: "required" %>
                    <%= f.email_field :email, placeholder: "Email", required: "required" %>
                    
                    <%= f.text_field :address_one, placeholder: "Address1", required: "required" %>
                    <%= f.text_field :address_two, placeholder: "Address2" %>
                    <%= f.number_field :zip_code, placeholder: "Zip / Postal Code", required: "required" %>
                    <%= f.text_field :mobile_number, placeholder: "Mobile Phone", required: "required" %>
                    <%= f.hidden_field :status, :value => 'active' %>
                </div>
              </div>
                <%= f.submit "Submit", class: "btn btn-primary" %>        
            </div>
          <% end %>  
        </div>
    </div>
    <div class="modal-footer">
      <%= submit_tag 'Cancel', :type => :reset, :class => "btn btn-danger", "data-dismiss" => "modal", "aria-hidden" => "true" %>
    </div>
  </div>     
</div>
  

app/views/checkouts/_edit_address_model_form.html.erb
<div class="container">
  <div class="modal fade" id="myModal1" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Edit Address</h4>
        </div>
        <div class="modal-body">
          <div class="shopper-informations">
            <div class="row">
              <%= form_for @addresses, :html => { :id=>'submit-form'} do |f| %>
                <div class="col-sm-12 clearfix">
                  <div class="bill-to">
                    <div class="form-one">
                      <%= f.text_field :name, placeholder: "Name" %>
                      <%= f.text_field :email, placeholder: "Email" %>
                      <%= f.text_field :address_one, placeholder: "Address1" %>
                      <%= f.text_field :address_two, placeholder: "Address2" %>
                      <%= f.text_field :zip_code, placeholder: "Zip / Postal Code" %>
                      <%= f.text_field :mobile_number, placeholder: "Mobile Phone" %>
                    </div>
                  </div>
                </div>
              <% end %>          
            </div>
        </div>
        <div class="modal-footer">
          <%= submit_tag "Submit", class: "btn btn-sucess", onClick: "$('#submit-form').submit()" %>
          <%= submit_tag 'Cancel', :type => :reset, :class => "btn btn-danger", "data-dismiss" => "modal", "aria-hidden" => "true" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/checkouts/_form.html.erb
<%= form_for(@checkout) do |f| %>
  <% if @checkout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@checkout.errors.count, "error") %> prohibited this checkout from being saved:</h2>
      <ul>
        <% @checkout.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/checkouts/_index.html.erb
<% if current_user.cart_items.present? %>
  <section id="cart_items">
    <div class="container">
      <div class="breadcrumbs">
        <ol class="breadcrumb">
          <li><%= link_to 'Home', root_url %></li>
          <li class="active">Check out</li>
        </ol>
      </div><!--/breadcrums-->
      <div class="step-one">
        <h2 class="heading">Step1</h2>
      </div>
      <%= button_tag "Add new address", class: "btn btn-primary", "data-toggle" => "modal","data-target" => "#myModal"%>
      <div class="shopper-informations">
        <div class="row">
          <% if current_user.addresses.present? %>
            <div class="container">
              <%if current_user.addresses.where(status: 'active').present? %>
                <div class="panel panel-info">
                  <div class="panel-body">
                    <% current_user.addresses.where(status: 'active').each do |address| %>
                        <div class="col-lg-4 well", style: "margin-left: 15px" >
                          <span><h4>Name: <%= address.name %></h4></span><br>
                          <span>Email: <%= address.email %></span><br>
                          <span>Mobile number: <%= address.mobile_number %></span><br>
                          <span>Address: <%= address.address_one%> <%= address.address_two %></span><br>
                          <span>PIN: <%= address.zip_code %></span><br><br> 
                          <i class="fa fa-trash-o"></i> 
                          <%= link_to "Delete", address_path(address, status: 'delete'), method: :put, data: { confirm: 'you want to delete?'} %>
                          &nbsp;&nbsp;&nbsp;&nbsp;
                          <i class="fa fa-pencil-square-o"></i></span>
                          <%= link_to "Edit", edit_address_path(address), remote: true %>
                          <br><br>
                          <%= link_to "Deliver on this address",  payment_review_path(address_id: address.id), class: "btn btn-default check_out" %>
                        </div>  
                    <% end %>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
          <div class="modal fade" id="myModal" role="dialog">
            <br><%= render 'checkouts/address_model_form' %> 
          </div>
        </div>
      </div>
      <div class="review-payment">
        <h2>Review & Payment</h2>
      </div>
      <div class="cart_info">
        <table class="table table-condensed">
          <thead>
            <tr class="cart_menu">
              <td class="image">Item</td>
              <td class="description"></td>
              <td class="price">Price</td>
              <td class="quantity">Quantity</td>
              <td class="total">Total</td>
              <td></td>
            </tr>
          </thead>
          <tbody>
            <% current_user.cart_items.each do |cart_item| %>
              <tr>
                <td class="cart_product">
                  <% if cart_item.product.pictures.first.present? %>
                    <%= image_tag(cart_item.product.pictures.first.image.url,class: 'cart-image', style: "width:100px;height:100px") %>
                  <% end %>
                </td>
                <td class="cart_description">
                  <h4 class="product_desc_align"><%= cart_item.product.name %></h4>
                </td>
                <td class="cart_price">
                  <p>&#8377; <%= cart_item.product.price %></p>
                </td>
                <td class="cart_quantity">
                  <div class="cart_quantity_button">
                    <%= link_to "+", cart_item_path(id: cart_item, qty: "plus"), method: :put , class: "cart_quantity_up", :remote => true %>
                    <%= number_field_tag :quantity, nil, min: 1, max: 20, onfocusout:"updateQuantity(#{cart_item.id},#{cart_item.product.id})", id: "#{cart_item.id}", class: "cart_quantity_input" , :remote => true, :value => cart_item.quantity %>
                    <%= link_to "-", cart_item_path(cart_item, qty: "minus"), method: :put, class: "cart_quantity_down", :remote => true %>
                  </div>
                </td>
                <td class="cart_total" >
                  <% @total = cart_item.product.price * cart_item.quantity %>
                  <p id="sub_total_<%= cart_item.id %>" class="cart_total_price">&#8377; <%= @total %></p>
                </td>
              </tr>
            <% end %>
            <tr>
              <td colspan="4">&nbsp;</td>
              <td colspan="2">
                <table class="table table-condensed total-result">
                  <tr>
                    <td>Cart Sub Total</td>
                    <td><div id="cart_sub_total">&#8377; <%= @sub_total %></div></td>
                  </tr>
                  <tr>
                    <td>Discount</td>
                    <td><div id="discount">&#8377; <%= @discount %></div></td>
                  </tr>
                  <tr>
                    <td>Exo Tax</td>
                    <td><div id="tax">&#8377; <%= @tax %></div></td>
                  </tr>
                  <tr class="shipping-cost">
                    <td>Shipping Cost</td>
                    <td><div id="shipping_cost">&#8377; <%= @shipping_cost %></div></td>                   
                  </tr>
                  <tr>
                    <td>Total</td>
                    <td><span id="sub_sub_total_">&#8377; <%= @final_total %></td>
                  </tr>
                </table>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </section> <!--/#cart_items-->
<% else %>
  <section id="cart_items">
    <div class="container">
      <div class="cart_info">
        <h3>Empty Cart</h3>
      </div>
    </div>
  </section>
<% end %>
<div>
  <div class="modal fade" id="edit-modal" role="dialog">
  </div>
</div>

app/views/checkouts/edit.html.erb
<h1>Editing Checkout</h1>
<%= render 'form' %>
<%= link_to 'Show', @checkout %> |
<%= link_to 'Back', checkouts_path %>

app/views/checkouts/index.html.erb
<div id="index_checkout">
  <%= render 'checkouts/index' %>
<div>

app/views/checkouts/new.html.erb
<h1>New Checkout</h1>
<%= render 'form' %>
<%= link_to 'Back', checkouts_path %>

app/views/checkouts/payment_review.html.erb
<section id="cart_items">
  <div class="container">
    <div class="breadcrumbs">
      <ol class="breadcrumb">
        <li><a href="#">Home</a></li>
        <li class="active">Check out</li>
      </ol>
    </div>
    <div class="shopper-informations">
    </div>
    <div class="review-payment">
      <h2>Review & Payment</h2>
    </div>
    <div class="cart_info">
      <table class="table table-condensed">
        <thead>
          <tr class="cart_menu">
            <td class="image">Item</td>
            <td class="description"></td>
            <td class="price">Price</td>
            <td class="quantity">Quantity</td>
            <td class="total">Total</td>
            <td></td>
          </tr>
        </thead>
        <tbody>
          <% current_user.cart_items.each do |cart_item| %>
            <tr>
              <td class="cart_product">
                <% if cart_item.product.pictures.first.present? %>
                  <%= image_tag(cart_item.product.pictures.first.image.url, class: 'cart-image', style: "width:100px;height:100px") %>
                <% end %>
              </td>
              <td class="cart_description">
                <h4 class="product_desc_align"><%= cart_item.product.name %></h4>
              </td>
              <td class="cart_price">
                <p>&#8377; <%= cart_item.product.price %></p>
              </td>
              <td class="cart_quantity">
                <div class="cart_quantity_button">
                 <p><%= cart_item.quantity %></p>
                </div>
              </td>
              <td class="cart_total" >
                <% @total = cart_item.product.price * cart_item.quantity %>
                <p id="sub_total_<%= cart_item.id %>" class="cart_total_price">&#8377; <%= @total %></p>
              </td>
            </tr>
          <% end %>
          <tr>
            <td colspan="4">&nbsp;</td>
            <td colspan="2">
              <table class="table table-condensed total-result">
                <tr>
                  <td>Cart Sub Total</td>
                  <td><div id="cart_sub_total">&#8377; <%= @sub_total %></div></td>
                </tr>
                <tr>
                  <td>Discount</td>
                  <td><div id="discount">&#8377; <%= @discount %></div></td>
                </tr>
                <tr>
                  <td>Exo Tax</td>
                  <td><div id="tax">&#8377; <%= @tax %></div></td>
                </tr>
                <tr class="shipping-cost">
                  <td>Shipping Cost</td>
                  <td><div id="shipping_cost">&#8377; <%= @shipping_cost %></div></td>                   
                </tr>
                <tr>
                  <td>Total</td>
                  <td><span id="sub_sub_total_">&#8377; <%= @final_total %></td>
                </tr>
              </table>
            </td>
          </tr>
        </tbody>
      </table>
      <%= link_to(orders_path(address_id: @address_id), method: :post, class: "btn btn-primary continue_to_payment") do  %>
      Continue to payment
      <% end %>
    </div>
  </div>
</section>

app/views/checkouts/show.html.erb
<%= link_to 'Edit', edit_checkout_path(@checkout) %> |
<%= link_to 'Back', checkouts_path %>