config/routes.rb
Rails.application.routes.draw do
  
  get 'reports/index'
  get 'reports/sales_report'
  get 'reports/customer_registered'
  get 'reports/coupon_used'
  resources :recommended_products
  resources :contacts
  resources :wishlists
  resources :transactions
  resources :orders do
    member do
      get 'cancel_order'
    end
  end
  resources :coupons
  resources :addresses
  resources :checkouts  
  get :payment_review, to: 'checkouts#payment_review'
  get :check_coupon_code, to: 'checkouts#check_coupon_code'
  resources :cart_items
  resources :product_categories
  resources :products
  resources :brand_categories
  resources :charges do
    member do
      get 'payment'
    end
  end
  resources :products
  resources :categories do
    resources :brands
  end
  resources :brands
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'home#index'
  get '*abc', :to => 'home#routing_error'

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :user
  has_many :orders
end

app/models/banner.rb
class Banner < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  has_many :pictures, as: :imageable
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  default_scope  { order(:name => :desc) }
  has_many :brand_categories
  has_many :categories, :through => :brand_categories
  has_many :products
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :user
  belongs_to :product

  def self.cart_total(cart_items,session)
    sub_total = 0
    discount = 0
    cart_items.each do |item|
      sub_total += (item.product.price.to_i * item.quantity.to_i) 
    end
    if session.present?
      coupon = Coupon.find_by(code: session)
      percent_off = coupon.percent_off
      discount = ((percent_off * sub_total) / 100)
      tax = 0.04 * sub_total
      shipping_cost = 40
      final_total = tax + sub_total + shipping_cost - discount
    else
      tax = 0.04 * sub_total
      shipping_cost = 40
      final_total = tax + sub_total + shipping_cost
    end
    return sub_total, discount, tax, shipping_cost, final_total
  end

  def self.update_cart(params_qty, params_quantity, cart_item)
    if params_qty == "minus"
      if cart_item.quantity == 1
        cart_item.quantity=1
      else
        cart_item.quantity -= 1
      end
    elsif params_qty == "plus"
      cart_item.quantity += 1
    else
      quantity = params_quantity.to_i
      if params_quantity == ""
        cart_item.quantity = @cart_item.quantity
      elsif params_quantity.to_i < 1
        cart_item.quantity = 1
      else
        cart_item.quantity = quantity
      end
    end
    return cart_item.quantity
  end

  def self.update_cart_item(cart_item, boolean, cart_item_quantity)
    if boolean.present?
      quantity_one = cart_item_quantity
      cart_item.quantity += quantity_one.to_i
    else
      cart_item.quantity += 1
    end
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :subcategories, class_name: "Category", foreign_key: "category_id", dependent: :destroy
  has_many :brands, :through => :brand_categories
  has_many :brand_categories
  belongs_to :category
  has_many :products, :through => :product_category
  has_many :product_category
end

app/models/checkout.rb
class Checkout < ActiveRecord::Base

  def self.cart_total(cart_items,session)
    sub_total = 0
    discount = 0
    cart_items.each do |item|
      sub_total += (item.product.price.to_i * item.quantity.to_i) 
    end
    if session.present?
      coupon = Coupon.find_by(code: session)
      percent_off = coupon.percent_off
      discount = ((percent_off * sub_total) / 100)
      tax = 0.04 * sub_total
      shipping_cost = 40
      final_total = tax + sub_total + shipping_cost - discount
    else
      tax = 0.04 * sub_total
      shipping_cost = 40
      final_total = tax + sub_total + shipping_cost
    end
    return sub_total,discount,tax,shipping_cost,final_total
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :user
end

app/models/coupon.rb
class Coupon < ActiveRecord::Base

  def self.destroy_coupon(cart_items, session)
    sub_total1 = 0
    discount = 0
    cart_items.each do |item|
      sub_total1 += (item.product.price.to_i * item.quantity.to_i) 
    end
    if session.present?
      coupon = Coupon.find_by(code: session)
      percent_off = coupon.percent_off
      discount = ((percent_off * sub_total1) / 100)
      tax = 0.04 * sub_total1
      shipping_cost = 40
      final_total = tax + sub_total1 + shipping_cost - discount
    else
      tax = 0.04 * sub_total1
      shipping_cost = 40
      final_total = tax + sub_total1 + shipping_cost
    end
    return sub_total1, discount, tax, shipping_cost, final_total
  end

end

app/models/coupon_used.rb
class CouponUsed < ActiveRecord::Base
  belongs_to :user
  belongs_to :order
  belongs_to :coupon
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :address
  has_many :orderitems
  default_scope -> { order(id: :desc) }
  after_update :track_order
  
  def track_order
    @order = Order.find(id)
    @track_order = Trackorder.new(status: @order.order_status, order_id: @order.id)
    @track_order.save
  end

  def self.set_sub_total(current_user)
    sub_total = 0
    current_user.cart_items.each do |item|
      sub_total += (item.product.price.to_i * item.quantity.to_i) 
    end
    return sub_total
  end
end

app/models/orderitem.rb
class Orderitem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :user
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :imageable, polymorphic: true
  mount_uploader :image, ImageUploader
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :pictures, as: :imageable
  belongs_to :brand
  has_many :product_category
  has_many :categories, :through => :product_category

  has_and_belongs_to_many(:products,
    :join_table => "recommended_products",
    :foreign_key => "product_id",
    :association_foreign_key => "recommended_product_id")
end

app/models/trackorder.rb
class Trackorder < ActiveRecord::Base
  belongs_to :order
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :user
  belongs_to :order
  belongs_to :orderitem
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  #validates :status, presence: true
  after_create :send_email
  has_many :wishlists, dependent: :destroy
  has_many :orders
  has_many :orderitems
  has_many :addresses
  has_many :coupon_useds
  has_many :transactions
  has_many :contacts
  devise :omniauthable, :omniauth_providers => [:facebook,:google_oauth2,:twitter]
  has_many :cart_items
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.firstname = auth.info.name
      user.password = Devise.friendly_token[0,20]
    end
  end
  
  def send_email
    UserMailer.welcome_email(self).deliver
  end       
end

app/models/wishlist.rb
class Wishlist < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/commonrender/_category_items.html.erb
<div class="category-tab"><!--category-tab-->
  <div class="col-sm-12">
    <ul class="nav nav-tabs">
      <%if @category.present? %>
        <%if @category.subcategories.present? %>
          <% @categories.each_with_index do |subcategory, index| %>
            <% if subcategory.category_id == @category.id %>
              <li class= <%= 'active' if params[:sub_category].to_s == subcategory.id.to_s %> >
                <%= link_to category_path(id: @category.id, sub_category: subcategory.id) do %>
                  <%= subcategory.name %>
                <% end %>
              </li>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </ul>
  </div>
  <div class="tab-content">
    <div class="tab-pane fade active in" id="tshirt" >
      <%if @products.present? %>
        <% @products.each do |product| %>
          <div class="col-sm-3">
            <div class="product-image-wrapper">
              <div id="wishlist-<%=product.id%>">
                <%= render partial: "home/wish_list_tag", locals: {product: product} %>
              </div>
              <div class="single-products">
                <div class="productinfo text-center">
                  <%= link_to product_path(product)do %>
                    <% if product.pictures.find_by(imageable_id: product.id).present? %>
                      <%= image_tag product.pictures.first.image %>
                    <% end %>
                    <h2>&#8377; <%=product.price %></h2>
                    <p><%= truncate(product.name, length: 22, omission: '...') %></p>
                  <% end %>
                  <%= link_to "Add to Cart",cart_items_path(product_id: product.id), method: :post, class: "fa fa-shopping-cart btn btn-default add-to-cart" %>
                </div> 
              </div>
            </div>
          </div>
        <% end %>
      <% else %>
        <h3 style="text-align: center;">Product not available</h3><br>
      <% end %>
    </div> 
  </div>
</div>

app/views/commonrender/_footer.html.erb
<footer id="footer">
  <div class="footer-top">
    <div class="container">
      <div class="row">
        <div class="col-sm-2">
          <div class="companyinfo">
            <h2><span>e</span>-shopper</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor</p>
          </div>
        </div>
        <div class="col-sm-7">
          <div class="col-sm-3">
            <div class="video-gallery text-center">
              <a href="#">
                <div class="iframe-img">
                  <%= image_tag "home/iframe1.png" %>
                </div>
                <div class="overlay-icon">
                  <i class="fa fa-play-circle-o"></i>
                </div>
              </a>
              <p>Circle of Hands</p>
              <h2>24 DEC 2014</h2>
            </div>
          </div>
          <div class="col-sm-3">
            <div class="video-gallery text-center">
              <a href="#">
                <div class="iframe-img">
                  <%= image_tag "home/iframe2.png" %>
                </div>
                <div class="overlay-icon">
                  <i class="fa fa-play-circle-o"></i>
                </div>
              </a>
              <p>Circle of Hands</p>
              <h2>24 DEC 2014</h2>
            </div>
          </div>
          <div class="col-sm-3">
            <div class="video-gallery text-center">
              <a href="#">
                <div class="iframe-img">
                  <%= image_tag "home/iframe3.png" %>
                </div>
                <div class="overlay-icon">
                  <i class="fa fa-play-circle-o"></i>
                </div>
              </a>
              <p>Circle of Hands</p>
              <h2>24 DEC 2014</h2>
            </div>
          </div>
          <div class="col-sm-3">
            <div class="video-gallery text-center">
              <a href="#">
                <div class="iframe-img">
                  <%= image_tag "home/iframe4.png" %>
                </div>
                <div class="overlay-icon">
                  <i class="fa fa-play-circle-o"></i>
                </div>
              </a>
              <p>Circle of Hands</p>
              <h2>24 DEC 2014</h2>
            </div>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="address">
            <%= image_tag "home/map.png" %>
            <p>505 S Atlantic Ave Virginia Beach, VA(Virginia)</p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="footer-widget">
    <div class="container">
      <div class="row">
        <div class="col-sm-2">
          <div class="single-widget">
            <h2>Service</h2>
            <ul class="nav nav-pills nav-stacked">
              <li><a href="#">Online Help</a></li>
              <li><a href="#">Contact Us</a></li>
              <li><a href="#">Order Status</a></li>
              <li><a href="#">Change Location</a></li>
              <li><a href="#">FAQ’s</a></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-2">
          <div class="single-widget">
            <h2>Quock Shop</h2>
            <ul class="nav nav-pills nav-stacked">
              <li><a href="#">T-Shirt</a></li>
              <li><a href="#">Mens</a></li>
              <li><a href="#">Womens</a></li>
              <li><a href="#">Gift Cards</a></li>
              <li><a href="#">Shoes</a></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-2">
          <div class="single-widget">
            <h2>Policies</h2>
            <ul class="nav nav-pills nav-stacked">
              <li><a href="#">Terms of Use</a></li>
              <li><a href="#">Privecy Policy</a></li>
              <li><a href="#">Refund Policy</a></li>
              <li><a href="#">Billing System</a></li>
              <li><a href="#">Ticket System</a></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-2">
          <div class="single-widget">
            <h2>About Shopper</h2>
            <ul class="nav nav-pills nav-stacked">
              <li><a href="#">Company Information</a></li>
              <li><a href="#">Careers</a></li>
              <li><a href="#">Store Location</a></li>
              <li><a href="#">Affillate Program</a></li>
              <li><a href="#">Copyright</a></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-3 col-sm-offset-1">
          <div class="single-widget">
            <h2>About Shopper</h2>
            <form action="#" class="searchform">
              <input type="text" placeholder="Your email address" />
              <button type="submit" class="btn btn-default"><i class="fa fa-arrow-circle-o-right"></i></button>
              <p>Get the most recent updates from <br />our site and be updated your self...</p>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="footer-bottom">
    <div class="container">
      <div class="row">
        <p class="pull-left">Copyright © 2017 E-SHOPPER Inc. All rights reserved.</p>
        <p class="pull-right">Designed by <span><a target="_blank" href="http://www.shyam-eshopper.herokuapp.com">Sham.....</a></span></p>
      </div>
    </div>
  </div>
</footer>

app/views/commonrender/_header.html.erb
<header id="header"><!--header-->
  <div class="header_top"><!--header_top-->
    <div class="container">
      <div class="row">
        <div class="col-sm-6">
          <div class="contactinfo">
            <ul class="nav nav-pills">
              <li><a href="#"><i class="fa fa-phone"></i> +91 9527604481</a></li>
              <li><a href="#"><i class="fa fa-envelope"></i> shyamshinde555@gmail.com</a></li>
              <% if current_user.present? %>
                <% if current_user.admin == true %>
                  <li><%= link_to "Admin Section", rails_admin_path %></li>
                  <li><%= link_to "Report", reports_index_path %></li>
                <% end %>
              <% end %>
            </ul>
          </div>
        </div>
        <% unless current_user.present? %>
          <div class="col-sm-6">
            <div class="social-icons pull-right">
              <ul class="nav navbar-nav">
                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
              </ul>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div><!--/header_top-->
  <div class="header-middle"><!--header-middle-->
    <div class="container">
      <div class="row">
        <div class="col-sm-4">
          <div class="logo pull-left">
            <%= link_to image_tag("home/logo.png", border: 0), root_path %>
          </div>
        </div>
        <div class="col-sm-8">
          <div class="shop-menu pull-right">
            <ul class="nav navbar-nav">
              <% if current_user.present? %>                
                <li class="dropdown">
                  <a href="#"><i class="fa fa-user"></i>Account</a>
                  <ul role="menu" class="sub-menu">
                    <li><%= link_to orders_path do %>
                      <i class="fa fa-reorder"> My orders</i><%end%>
                    </li>
                    <li><%= link_to wishlists_path do %>
                      <i class="fa fa-heart"> Wishlists</i><%end%>
                    </li>
                    <% if current_user.cart_items.present? %>
                      <li><%= link_to "Checkout", checkouts_path%></li>
                    <% end %>
                    <li><%= link_to edit_user_registration_path do %>
                      <i class="fa fa-edit" aria-hidden="true"> Edit Profile</i><% end %>
                    </li>
                    <li><%= link_to contacts_path do %>
                      <i class="fa fa-phone" aria-hidden="true"> Contact Us</i><%end %>
                    </li></br>
                  </ul>
                </li>
                  <% if current_user.cart_items.present? %>
                    <li><%= link_to cart_items_path do %><i class="fa fa-shopping-cart"aria-hidden="true" id="cart"%> Cart (<%= current_user.cart_items.count%>)</i> <% end %></li>
                  <% end %>
                <li><%= link_to  destroy_user_session_path, method: :delete do %><i class="fa fa-sign-out" %> Logout</i><% end %></li>
              <% else %>
                <% if current_page?(user_session_path) %>
                   <li><%= link_to new_user_registration_path do %><i class="fa fa-lock" aria-hidden="true"> Signup</i><% end %></li>
                <% else %>
                  <li><%= link_to user_session_path do %><i class="fa fa-lock" aria-hidden="true"></i> Login<% end %></li>
                <% end %>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div><!--/header-middle-->
</header><!--/header-->

app/views/commonrender/_left_sidebar.html.erb
<div class="left-sidebar">
  <h2>Category</h2>
  <div class="panel-group category-products" id="accordian">
     <% @categories.each do |category| %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <%if !category.category_id.present? %>
          <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#accordian" href="#<%= category.id %>">
              <% if category.brands.present? %>
                <span class="badge pull-right"><i class="fa fa-plus"></i></span>
              <%end%>   
              <%= link_to category_path(category) do %>
                <%= category.name %>
              <%end%>
              <%end%>     
            </a>
          </h4>
        </div>
        <div id="<%= category.id %>" class="panel-collapse collapse <%= 'in' if @category.id == category.id || @category.category_id == category.id %>">
          <% if category.brands.present? %>
            <div class="panel-body">
              <ul>
                <% category.brands.each do |brand| %>
                  <li class="<%= "brand_underline" if current_page?category_brand_path(brand,category_id: category) %>">
                    <%= link_to category_brand_path(brand,category_id: category) do %>
                    <%= brand.name%><% end %>
                  </li>
                <%end%>
              </ul>
            </div>
          <%end%>
        </div>
      </div>
    <% end %>
  </div><!--/category-products-->
  <div class="brands_products"><!--brands_products-->
    <h2>Brands</h2>
    <div class="brands-name">
      <ul class="nav nav-pills nav-stacked">
        <% @brands.each do |brand| %>
          <%if brand.products.present? %>
            <li><%= link_to brands_path(id: brand.id) do %>
              <span class="pull-right">(<%= brand.products.count %>)</span><%= brand.name %>
               <%end%>
            </li>
          <%end%>
        <%end%>
      </ul>
    </div>
  </div><!--/brands_products-->
</div>

app/views/commonrender/_recommended_items.html.erb
<div class="recommended_items"><!--recommended_items-->
  <h2 class="title text-center">recommended items</h2>
  <div id="recommended-item-carousel" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="item active"> 
      </div>
      <div class="item"> 
      </div>
    </div>
     <a class="left recommended-item-control" href="#recommended-item-carousel" data-slide="prev">
      <i class="fa fa-angle-left"></i>
      </a>
      <a class="right recommended-item-control" href="#recommended-item-carousel" data-slide="next">
      <i class="fa fa-angle-right"></i>
      </a>      
  </div>
</div><!--/recommended_items-->

app/views/commonrender/_slider.html.erb
<section id="slider"><!--slider-->
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <div id="slider-carousel" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators">
            <% @banners.each_with_index do |banner, index| %>
              <li data-target="#slider-carousel" data-slide-to="<%= index %>" class="<%= index == 0 ? 'active' : '' %>"></li>
            <% end %>
          </ol>
          <div class="carousel-inner" role="listbox">
            <% @banners.each_with_index do |banner, index| %>     
              <div class="item <%= index == 0 ? 'active' : '' %>">
                <div class="col-sm-6">
                  <h1><span><%= banner.title %></h1>
                  <p><%= banner.content %></p>
                  <button type="button" class="btn btn-default get">Get it now</button>
                </div>
                <div class="col-sm-6">
                  <% if banner.pictures.find_by(imageable_id: banner.id).present? %>
                    <%= image_tag banner.pictures.find_by(imageable_id: banner.id).image, class: "girl img-responsive" %>
                    <%= image_tag "home/pricing.png", class: "pricing" %>
                  <%end%>
                </div>
              </div>
            <% end %>
          </div>
          </div>
          <a href="#slider-carousel" class="left control-carousel hidden-xs" data-slide="prev">
            <i class="fa fa-angle-left"></i>
          </a>
          <a href="#slider-carousel" class="right control-carousel hidden-xs" data-slide="next">
            <i class="fa fa-angle-right"></i>
          </a>
        </div>
      </div>
    </div>
  </div>
</section><!--/slider-->