config/routes.rb
Rails.application.routes.draw do
  
  get 'reports/index'
  get 'reports/sales_report'
  get 'reports/customer_registered'
  get 'reports/coupon_used'
  resources :recommended_products
  resources :contacts
  resources :wishlists
  resources :transactions
  resources :orders do
    member do
      get 'cancel_order'
    end
  end
  resources :coupons
  resources :addresses
  resources :checkouts  
  get :payment_review, to: 'checkouts#payment_review'
  get :check_coupon_code, to: 'checkouts#check_coupon_code'
  resources :cart_items
  resources :product_categories
  resources :products
  resources :brand_categories
  resources :charges do
    member do
      get 'payment'
    end
  end
  resources :products
  resources :categories do
    resources :brands
  end
  resources :brands
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'home#index'
  get '*abc', :to => 'home#routing_error'

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :pictures, as: :imageable
  belongs_to :brand
  has_many :product_category
  has_many :categories, :through => :product_category

  has_and_belongs_to_many(:products,
    :join_table => "recommended_products",
    :foreign_key => "product_id",
    :association_foreign_key => "recommended_product_id")
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :set_products, only: [:index, :show]

  # GET /products
  # GET /products.json
  def index
    
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @brands = Brand.all
    @categories = Category.all
    @cart_item = CartItem.new
    @category = Category.first
    @recommended_products = @product.products 
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    def set_products
      @products = Product.all
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :short_description, :long_description, :status, :brand_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :short_description %><br>
    <%= f.text_field :short_description %>
  </div>
  <div class="field">
    <%= f.label :long_description %><br>
    <%= f.text_area :long_description %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.check_box :status %>
  </div>
  <div class="field">
    <%= f.label :brand_id %><br>
    <%= f.text_field :brand_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_left_sidebar.html.erb
<div class="left-sidebar">
  <h2>Category</h2>
  <div class="panel-group category-products" id="accordian"><!--category-productsr-->
    <% @categories.each do |category| %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <%if !category.category_id.present? %>
            <h4 class="panel-title">
              <a data-toggle="collapse" data-parent="#accordian" href="#<%= category.id %>">
                <% if category.brands.present? %>
                  <span class="badge pull-right"><i class="fa fa-plus"></i></span>
                <%end%>   
                <%= link_to category_path(category) do %>
                  <%= category.name%>
                <%end%>
              </a>
            </h4>
          <%end%>
        </div>
        <% if category.brands.present? %>
          <div id="<%= category.id %>" class="panel-collapse collapse <%= category.id == @category.id ? 'in' : '' %>" >
            <div class="panel-body">
              <ul>
                <% category.brands.each do |brand|%>
                  <li class="<%= "brand_underline" if current_page?category_brand_path(brand, category_id: category) %>">
                    <%= link_to category_brand_path(brand, category_id: category) do %>
                    <%= brand.name%>
                  <%end%></li>
                <%end%>
              </ul>
            </div>
          </div>
        <%end%>
      </div>
    <% end %>
  </div><!--/category-products-->
  <div class="brands_products"><!--brands_products-->
    <h2>Brands</h2>
    <div class="brands-name">
      <ul class="nav nav-pills nav-stacked">
        <% @brands.each do |brand|%>
          <%if brand.products.present? %>
            <li><%= link_to brands_path(id: brand.id) do%>
              <span class="pull-right">(<%= brand.products.count %>)</span><%= brand.name %>
              <%end%>
            </li>
          <%end%>
        <%end%>
      </ul>
    </div>
  </div><!--/brands_products-->
  <div class="price-range"><!--price-range-->
    <h2>Price Range</h2>
    <div class="well text-center">
      <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="600" data-slider-step="5" data-slider-value="[250,450]" id="sl2" ><br />
      <b class="pull-left">$ 0</b> <b class="pull-right">$ 600</b>
    </div>
  </div><!--/price-range-->
  <div class="shipping text-center"><!--shipping-->
    <%= image_tag "home/shipping.jpg" %>
  </div><!--/shipping-->
</div>

app/views/products/_recommended_items.html.erb
<h2 class="title text-center">recommended items</h2>
<div id="recommended-item-carousel" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <% if @recommended_products.present? %>
      <% @recommended_products.each_slice(3).with_index do |products,index|%>
        <div class="item <%= index == 0 ? 'active' : '' %>">
          <%products.each do |product|%>
            <div class="col-sm-4">
              <div class="product-image-wrapper">
                <div class="single-products">
                  <div class="productinfo text-center">
                    <div id="wishlist-<%=product.id%>">
                      <%= render partial: "home/wish_list_tag",locals: {product: product} %>
                    </div>
                    <%= link_to product_path(product)do%>
                      <%if product.pictures.find_by(imageable_id: product.id).present? %>
                        <%= image_tag product.pictures.first.image %>
                      <%end%>
                      <h2>&#8377; <%=product.price%></h2>
                      <p><%= truncate(product.name, length: 22, omission: '...') %></p>
                    <%end%>
                      <%= link_to "Add to Cart",cart_items_path(product_id: product.id),method: :post, class: "fa fa-shopping-cart btn btn-default add-to-cart"%> 
                  </div>
                </div>
              </div>
            </div>
          <%end%>
        </div>
      <%end%>
    <%else%>
      <h3 style="text-align: center;">Recommended products not available</h3>
    <%end%>
  </div>
   <a class="left recommended-item-control" href="#recommended-item-carousel" data-slide="prev">
    <i class="fa fa-angle-left"></i>
    </a>
    <a class="right recommended-item-control" href="#recommended-item-carousel" data-slide="next">
    <i class="fa fa-angle-right"></i>
    </a>      
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>
<%= render 'form' %>
<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing Products</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Short description</th>
      <th>Long description</th>
      <th>Status</th>
      <th>Brand</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.short_description %></td>
        <td><%= product.long_description %></td>
        <td><%= product.status %></td>
        <td><%= product.brand %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>
<%= render 'form' %>
<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
  <section>
    <div class="container">
      <div class="row">
        <div class="col-sm-3">
          <%= render 'left_sidebar'%>
        </div>
        <div class="col-sm-9 padding-right">
          <div class="product-details"><!--product-details-->
            <div class="col-sm-5">
              <div class="view-product">
                <div id="wishlist-<%=@product.id%>">
                  <%= render partial: "home/wish_list_tag", locals: {product: @product} %>
                </div>
                <% if @product.pictures.find_by(imageable_id: @product.id).present? %>
                  <%= image_tag @product.pictures.first.image, id: "show" %>
                <%end%>
                <h3>ZOOM</h3>
              </div>
              <div id="similar-product" class="carousel slide" data-ride="carousel">
                  <!-- Wrapper for slides -->
                  <div class="carousel-inner">
                    <% @product.pictures.each_slice(3).with_index do |pictures,index|%>
                      <div class="item <%= index == 0 ? 'active' : '' %>">
                        <% pictures.each do |picture|%>
                          <%= image_tag(picture.image, style: "width:80px;height:80px", onmouseover: "showImage('#{picture.image.url}')")%>
                        <%end%>
                      </div>
                    <%end%>
                  </div>
                  <!-- Controls -->
                  <a class="left item-control" href="#similar-product" data-slide="prev">
                  <i class="fa fa-angle-left"></i>
                  </a>
                  <a class="right item-control" href="#similar-product" data-slide="next">
                  <i class="fa fa-angle-right"></i>
                  </a>
              </div>
            </div>
            <div class="col-sm-7">
              <div class="product-information">
                <%= image_tag "product-details/new.jpg",class: "newarrival", alt: "" %>
                <h2><%=@product.name%></h2>
                <%= image_tag "product-details/rating.png" %><br>
                <span>
                  <span>&#8377; <%=@product.price%></span>
                  <div class="pull-right">
                    <%= form_for @cart_item do |f|%>
                      <%= f.label :quantity %>
                      <%= f.number_field :quantity, min: 1,value: 1 %>
                      <%= hidden_field_tag :product_id, @product.id %>
                      <%= hidden_field_tag :boolean, true %>
                      <%= button_tag "Add to cart", class: "btn btn-fefault cart fa fa-shopping-cart"  %>
                    <%end%>
                  </div>
                </span>
                <p><b>Availability:</b> In Stock</p>
                <p><b>Condition:</b> New</p>
                <%if @product.brand.present? %>
                  <p><b>Brand:</b><%=@product.brand.name%></p>
                <%end%>
                <%= social_share_button_tag(@product.name) %>
              </div><!--/product-information-->
            </div>
          </div><!--/product-details-->
          <div class="recommended_items"><!--recommended_items-->
            <%= render 'recommended_items' %>
          </div><!--/recommended_items-->
        </div>
      </div>
    </div>
  </section>
  